apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitlyfe-api
  namespace: argocd
spec:
  project: default
  source:
    # TODO: update if your GitHub repo name differs
    repoURL: https://github.com/ShujaAhmed786/FitLyfe.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: fitlyfe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
